@echo off
echo Use either a ReSharper ".argr" file or a Visual Studio ".dgml" file generated by the NuGet package visualizer, pass the relative path to the file as an argument
echo Check the wix fragment folder for the output
Powershell.exe -executionpolicy remotesigned -File CreateXmlForWixAndNuGet.ps1 %1
pause